CATEGORY_KEYWORD_MAPPING = {
    "Groceries": ["SUPERVALU", "TESCO"],
    "Fees": ["FEE", "INTEREST CHARGED"],
    "Pharmacy": ["PHARM", "PHARMA", "PHARMACY"],
    "Doctors": ["MED", "VDC-CHURCHTOWN"],
    "Car Insurance": ["AXA"],
    "Life Insurance": ["AVIVA"],
    "Amazon Prime": ["AMZNPRIME"],
    "Entertainment": ["DISNEY", "*YouTub", "discovery+", "VDP-DISNEY PLUS"],
    "Loan": ["LOAN"],
    "ChatGPT": ["CHATGPT"],
    "Revolut": ["Revolut"],
    "Internet": ["THREE IRELAND"],
    "Petrol": [
        "FUEL",
        "VDC-FAIRVIEW SERVI",
        "VDP-MAXOL",
        "VDC-CIRCLE K",
    ],
    "Converge": ["CONVERGE"],
    "Lotto": ["LOTTER"],
    "Web Hosting": ["HEROKU"],
    "Cloud Storage": ["VDP-Microsoft*Micr"],
    "Electric": ["VDP-PREPAYPOWER"],
    "Phone": ["VDP-VODAFONE"],
    "Audible": ["VDP-Audible UK"],
    "Savings": ["SAVINGS"],
    "Credit Card": ["CLICK VISA"],
    "Rent": ["RENT"],
    "Maintenance": ["MTCE"],
    "Investments": ["VDP-Uphold"],
}
