# Generated by Django 4.2.4 on 2023-08-06 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_alter_account_user_alter_transaction_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='account_number',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
