# Generated by Django 4.2.4 on 2023-08-06 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_account_account_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='description',
            new_name='trans_type',
        ),
    ]
